### ISSUE TITLE
Plans on additional rack variants using 1U rows

### ISSUE THREAD

**Issue by fxwiegand** [KevinKeWang/tiny_rack#3]
Hey 👋🏻 

Many thanks for creating these amazing cases they certainly do look very good and the documentation is outstanding! Do you plan to add other case variants with 1U rows as well? This would definitely be interesting to me and probably others as well!

Best greetings!

Felix from [wgd modular](https://www.instagram.com/wgdmodular/)

**Comment by KevinKeWang** [comment]
Hello!

I won't be considering adding 1U track in the near future. as I don't think it looks too coherent on a 2x44hp.
It is possible to add 1U track to a single row of small boxes. you can make a simple modification via plasticity. I have uploaded the plasticity source project file. Similarly, modifying the width of the boxes via plasticity is very simple. 

Thank you for your support!

**Comment by KevinKeWang** [comment]
> Hey 👋🏻
> 
> Many thanks for creating these amazing cases they certainly do look very good and the documentation is outstanding! Do you plan to add other case variants with 1U rows as well? This would definitely be interesting to me and probably others as well!
> 
> Best greetings!
> 
> Felix from [wgd modular](https://www.instagram.com/wgdmodular/)

Hello!

I won't be considering adding 1U track in the near future. as I don't think it looks too coherent on a 2x44hp.
It is possible to add 1U track to a single row of small boxes. you can make a simple modification via plasticity. I have uploaded the plasticity source project file. Similarly, modifying the width of the boxes via plasticity is very simple.

Thank you for your support!
