### ISSUE TITLE
Shallower version of 2x44HP rack

### ISSUE THREAD

**Issue by jhbruhn** [KevinKeWang/tiny_rack#4]
Hi! Really awesome design of cases and incredibly well documented!! 

The 2x44HP Rack currently has quite a lot of space behind the modules. For Setups with mostly SMD-based modules with a single PCB, it could be made more compact. I tried to reduce the depth in the plasticity files (thanks for providing), but utterly failed. Did I miss some parameter setting somewhere, or a central sketch view?

Thanks a bunch!

**Comment by KevinKeWang** [comment]
> tried

The plasticity file is fully editable. What is the exact problem?

**Comment by KevinKeWang** [comment]
> Hi! Really awesome design of cases and incredibly well documented!! 
> 
> 
> 
> The 2x44HP Rack currently has quite a lot of space behind the modules. For Setups with mostly SMD-based modules with a single PCB, it could be made more compact. I tried to reduce the depth in the plasticity files (thanks for providing), but utterly failed. Did I miss some parameter setting somewhere, or a central sketch view?
> 
> 
> 
> Thanks a bunch!

The plasticity file is fully editable. What is the exact problem?
